[project]
name = "support-distribution-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aspose-cad>=26.7",
    "ezdxf>=1.4.4",
    "matplotlib>=3.11.1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.20.0",
    "pylint>=4.0.5",
]
